version: '3'
services:
  express-template:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-template
    environment:
      - NODE_ENV=dev
    # Uncomment the following lines to use an env file
    # env_file:
    #   - .env
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command:
      - npm
      - run
      - start:dev
